### ISSUE TITLE
Suggestion: More configuration wait_for_txt 

### ISSUE THREAD

**Issue by Chippit** [felixfontein/ansible-acme#79]
As it currently stands, when using a DNS challenge, the role [will use the `wait_for_txt` module](https://github.com/felixfontein/ansible-acme/blob/0bdf04c9ee042edd4a00ff585287812aba354ccd/roles/acme_certificate/tasks/dns-cloudflare-create.yml#L20) with a 2 minute timeout.

In our environment where we have an internal caching DNS server (that also serves important intranet-only addresses that the rest of our playbooks need, on the same domain name), the propagation test generally tends to fail.

It would be convenient to add role variables to:
- Control the timeout
- Override the server used by the test, so we can change it to use an upstream server without changing the system DNS server of the ansible controller.
- Or optionally just disable it entirely.

**Comment by felixfontein** [comment]
Hmm, skipping that step in total is not a good idea, since the ACME server's validation will fail if the records haven't been set up yet.

Making the timeout configurable, and allow to configure the DNS servers used (https://docs.ansible.com/ansible/devel/collections/community/dns/wait_for_txt_module.html#parameter-server) definitely makes sense though.

**Comment by felixfontein** [comment]
I've implemented this in #80.

**Comment by Chippit** [comment]
Thanks so much for the quick fix! This will be very helpful for us.
